Regular payments
Selentiy/ApiTemplate-PI-318-1 pull request #10
Opened 2019-10-29 13:54 UTC by BabenkoA

2019-10-30 06:32 UTC, ghost requested changes

2019-10-30 06:32 UTC, anton-beetroot-23071996 commented on App.Common/Repositories/IRegularPaymentsRepository.cs
> +        void CreateRegularPayment(RegularPayment regularPayment);
Create method should returns either identifier of created entity, or the entire entity

2019-10-31 11:35 UTC, BabenkoA commented on App.Common/Models/RegularPayment.cs
> +        public double Payment { get; set; }
Amount

2019-10-31 11:37 UTC, BabenkoA commented on App.RegularPayments/PaymentsManager.cs
> +            return GetRegularPaymentsById(id).DateOfLastPay.AddDays(GetRegularPaymentsById(id).Period);
make only 1 request to GetRegularPaymentsById

2019-10-31 11:38 UTC, BabenkoA commented on App.RegularPayments/Repositories/InMemoryRegularPaymentRepository.cs
> +            return (regularpayments.Count()) == (check + 1);
check if the same id exists

2019-11-04 09:27 UTC, merged