Stocks
Selentiy/ApiTemplate-PI-318-1 pull request #11
Opened 2019-10-31 11:24 UTC by MariiaMoroz

2019-10-31 11:48 UTC, MariiaMoroz commented on App.Stocks/Controllers/StocksController.cs
> +				return BadRequest();
not found

2019-10-31 11:52 UTC, MariiaMoroz commented on App.Stocks/Services/CompaniesManager.cs
> +		IEnumerable<CompanyView> GetCompaniesWithActiveStocks();
BAL shouldnt manage Dto classes. All mapping logic and View classes should be moved to controller

2019-10-31 11:53 UTC, MariiaMoroz commented on App.Stocks/View/StockView.cs
> +		public string Company_Name { get; set; }
Company_Name => CompanyName

2019-11-01 19:39 UTC, anton-beetroot-23071996 commented
@MariiaMoroz Ожидаю оговоренных изменений чтобы смерджить пулл реквест. Если пулл реквест не смерджен - лабораторная не засчитывается

2019-11-01 19:41 UTC, ghost requested changes
Изменения не внесены

2019-11-06 20:11 UTC, ghost approved these changes

2019-11-06 20:11 UTC, merged