Loans
Selentiy/ApiTemplate-PI-318-1 pull request #2
Opened 2019-10-10 02:00 UTC by Kurimoire

2019-10-10 20:52 UTC, ghost requested changes

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Common/App.Common.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
What is the reason of adding this packages to the solution ? Did you use it in the code ?

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Controllers/LoansController.cs
> +
The formatting of the file is broken

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Controllers/LoansController.cs
> +            readonly IAnotherService _anotherService;
what is the purpose of AnotherService ?

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Controllers/LoansController.cs
> +            public ActionResult<IEnumerable<string>> GetActiveLoans()
Endpoint, according to the name, should return a list of loans, but it returns a list of strings. Why ?

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Controllers/LoansController.cs
> +        public ActionResult<IEnumerable<string>> GetAmountOfPaymentsLeft(int Id)
The route for this endpoint should be like "api/loans/{id}/paymentsleft"
The route "api/loans/{Id}" should just return the loan object by it`s Id

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Interface/ILoan.cs
> +    public interface ILoan
Do we need an interface for DTO model ?

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Interface/ILoanManger.cs
> +        IEnumerable<string> GetValues();
What does it mean "GetValue" returning array of strings in ILoanManager ?

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Interface/ILoanRepo.cs
> +    public interface ILoanRepo
ILoanRepo -> ILoanRepository
Don`t crop the name of the interfaces and classes

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Models/Loan.cs
> +            LoanBalance = MoneyTaken - MoneyReturned + (MoneyTaken * NumberOfPayments * PercentPerAnnum / 12) ;
LoadBalance should be readonly property with only "get" part, which should return expression, which is currently calculated in the constructor

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.Loans/Services/AnotherService.cs
> +    public interface IAnotherService
What is the purpose of this class and interface ?

2019-10-10 20:52 UTC, anton-beetroot-23071996 commented on App.TestModule/App.Example.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" />
1) Why did you modified the Example solution (you should not make changes to Example part)
2) For what did you use this packages ?

2019-10-11 00:29 UTC, Kurimoire commented on App.Common/App.Common.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
У меня были проблемы с запуском проекта, и возникали конфликты версий пакетов nuget и поэтому переустанавливал пакеты, после чего проект заработал.

2019-10-11 00:36 UTC, Kurimoire commented on App.Loans/Controllers/LoansController.cs
> +            readonly IAnotherService _anotherService;
Я использую AnotherService чисто для подключения модуля. Далее, в последующих лабораторных работах он будет реализован более обширно , ибо в этой работе согласно требуемому функционалу, мы не нуждались в его реализации.

2019-10-11 00:44 UTC, Kurimoire commented on App.Loans/Interface/ILoanManger.cs
> +        IEnumerable<string> GetValues();
Values - значения, и метод возвращает значения, правда в формате стринга , для дальнейшего использования в контролере.
Переименую.

2019-10-11 00:50 UTC, Kurimoire commented on App.Loans/Models/Loan.cs
> +            LoanBalance = MoneyTaken - MoneyReturned + (MoneyTaken * NumberOfPayments * PercentPerAnnum / 12) ;
Нет, в данном случае, если смотреть внимательно код, то у нас реализовано автоматическое свойство для работы с этим полем, а само поле определено как приватное и инициализируется только в конструкторе. 
![image](https://user-images.githubusercontent.com/55829187/66616603-2b197f80-ebda-11e9-8ce9-e621655875b8.png)

2019-10-11 00:52 UTC, Kurimoire commented on App.Loans/Services/AnotherService.cs
> +    public interface IAnotherService
Я использую AnotherService чисто для подключения модуля. Далее, в последующих лабораторных работах он будет реализован более обширно , ибо в этой работе согласно требуемому функционалу, мы не нуждались в его реализации.

2019-10-11 00:56 UTC, Kurimoire commented on App.TestModule/App.Example.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" />
У меня были проблемы с запуском проекта, и возникали конфликты версий пакетов nuget и поэтому переустанавливал пакеты, после чего проект заработал.

2019-10-11 00:59 UTC, Kurimoire commented on App.Loans/Interface/ILoan.cs
> +    public interface ILoan
Так более правильнее, и если в дальнейшем нам нужно будет создать ещё одну модель кредита (отличающуюся сложностью подсчёта процентов или рассрочку, тогда нам понадобиться данный интерфейс).Грубо говоря , интерфейс лишним не бывает

2019-10-16 20:48 UTC, anton-beetroot-23071996 commented
Пожалуйста, придите на пару, мы вместе с вами разберем ваши проблемы с лишними пакетами

2019-10-16 20:49 UTC, ghost requested changes
Коментарии по лишним пакетам все еще актуальны

2019-10-27 11:17 UTC, anton-beetroot-23071996 commented
Ожидаю вас на паре для защиты лабораторной работы (и дискуссии по вашему коду)

2019-10-27 11:25 UTC, ghost requested changes
ожидаю вас на паре для защиты лабораторной работы

2019-11-06 06:21 UTC, Kurimoire commented on App.Loans/Interface/ILoan.cs
> +        string AmountOfPaymentsLeft();
string -> int

2019-11-06 06:23 UTC, Kurimoire commented on App.Loans/Interface/ILoanManger.cs
> +        IEnumerable<string> GetValuesInStringArray();
string -> object of type Loan

2019-11-06 06:24 UTC, Kurimoire commented on App.Loans/Interface/ILoanRepository.cs
> +        IEnumerable<string> GetValues();
1) more concrete method name
2) string -> object of Type Loan

2019-11-06 06:26 UTC, Kurimoire commented on App.Loans/Services/AnotherService.cs
> +    public interface IAnotherService
Still axctual

2019-11-06 06:27 UTC, Kurimoire commented on App.Loans/Models/Loan.cs
> +            LoanBalance = MoneyTaken - MoneyReturned + (MoneyTaken * NumberOfPayments * PercentPerAnnum / 12) ;
Still actual

2019-11-06 06:29 UTC, Kurimoire commented on App.Loans/Services/LoansManager.cs
> +        public IEnumerable<string> AmountOfPaymentsLeft(int Index)
Index -> Id

2019-11-10 22:59 UTC, ghost approved these changes

2019-11-10 22:59 UTC, merged