Users
Selentiy/ApiTemplate-PI-318-1 pull request #6
Opened 2019-10-22 09:56 UTC by MariaTeslia

2019-10-27 11:10 UTC, ghost requested changes

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Stocks/App.Stocks.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
Зачем вы вносили изменения в модуль другого студента ?

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Controllers/UsersController.cs
> +            var serviceCallResult = _usersManager.GetListActiveUsers().ToList();
GetList...ToList()
метод вашего интерфейса должен называться просто GetActiveUsers, если он не возвращает list

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Controllers/UsersController.cs
> +            _usersManager.BlockOrUnblockUserById(id);
нарушение single responsibility, метод должен иметь только одну ответственность, то есть либо блокировать, либо разблокировать. Разделите этот метода на block и unblock

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Models/User.cs
> +        public bool BlockStatus { get; set; }
если у вас булевая переменная, то она должна называться IsBlocked. Если ваше поле называется ...Status, то оно должно содержать статус, то есть быть enum/string enum

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Repository/InMemoryUsersRepository.cs
> +
лишняя новая строка

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Repository/InMemoryUsersRepository.cs
> +    public class InMemoryUsersRepository : IInMemoryUsersRepository, ITransientDependency
ваш репозиторий обьявлен как ITransientDependency, то есть на каждый запрос у вас будет создаватся новый репозиторий, следовательно внесенные изменения не будут сохранятся

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Repository/InMemoryUsersRepository.cs
> +            users[3] = new User("AntonBeetroot", "full-kek");
"👮  Full-kek tech lead developer" !

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Services/UsersManager.cs
> +        void BlockOrUnblockUserById(int id);
разделите метод на 2

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Services/UsersManager.cs
> +        InMemoryUsersRepository repository = new InMemoryUsersRepository();
ваш manager зависит от реализации, это неправильно. Он должен принимать интерфейс (!) через конструктор. DI система это сама обработает

2019-10-27 11:10 UTC, anton-beetroot-23071996 commented on App.Users/Services/UsersManager.cs
> +        InMemoryUsersRepository repository = new InMemoryUsersRepository();
Вам нужно сделать так же как у вас в контроллере

2019-10-27 20:11 UTC, MariaTeslia commented on App.Stocks/App.Stocks.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
Из-за того что небыла подключена данная библиотека , проэкт не запускался.Не давая при этом возможности для проверки работоспособности моего проэкта.(По сути эта библиотека должна быть подключена во всех проэктах,можете сами посмотреть и в этом убедиться.)

2019-10-27 20:19 UTC, MariaTeslia commented on App.Users/Repository/InMemoryUsersRepository.cs
> +            users[3] = new User("AntonBeetroot", "full-kek");
Пароль неможет содержать пробелов)

2019-10-27 21:28 UTC, ghost requested changes

2019-10-27 21:28 UTC, anton-beetroot-23071996 commented on App.Users/Repository/InMemoryUsersRepository.cs
> +{   public interface IInMemoryUsersRepository
имя вашего репозитория нарушает абстракцию, так как содержит детали реализации. Ваш интерфейс должен скрывать детали реализации хранилища юзеров. Для любой реализации должен быть 1 интерфейс IUsersRepository, а реализации могут быть: InMemoryUsersRepository, DbMsSqlUsersRepository, DbOracleUsersRepository, ApiSomeExternalServiceUsersRepository и тд.

2019-10-27 21:28 UTC, anton-beetroot-23071996 commented on App.Users/Models/User.cs
> +            return $"User Login: {Login}" + (IsBlocked == false? " Active user " : " User are blocked. ");
```suggestion
            return $"User Login: {Login}" + (IsBlocked ? "User is blocked." : "Active user");
```

2019-10-27 21:28 UTC, anton-beetroot-23071996 commented on App.Users/Models/User.cs
> +        //if true-unblocked
ваш комментарий некорректен и сбивает с толку

2019-10-27 21:29 UTC, anton-beetroot-23071996 commented on App.Stocks/App.Stocks.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
Но если вы откатили изменения, значит оно может работать и без этой ссылки ?)

2019-10-27 21:29 UTC, anton-beetroot-23071996 commented
Жду вас на паре для защиты лабораторной работы

2019-11-01 19:48 UTC, ghost requested changes
Жду вас на паре для защиты лабораторной работы

2019-12-12 11:03 UTC, ghost approved these changes

2019-12-12 11:04 UTC, merged